### ISSUE TITLE
Integration

### ISSUE THREAD

**Issue by afavata** [linchpin/magento2-advanced-sorting#1]
Hi Linchpin, 

I find your module very useful but I do not know how to integrate in the current Magento 2.2.3 installation.

Any tips???

Thanks

**Comment by moneef** [comment]
Just Forked and added composer to this, you can use `composer require linchpin/magento2-advanced-sorting --dev` to install.

i have requested a pull request to merge with `master`

**Comment by aaronware** [comment]
This has been merged into master thanks to @moneef
